## define the postgros volume 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-vol
  namespace: mail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-disk
  volumeMode: Filesystem

## define the config volume for both mail-core & exim4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-vol
  namespace: mail
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: csi-nas
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exim-log-data
  namespace: mail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-disk
