apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openlookeng-summary
resources:
- openlookeng-summary-deployment.yaml
- openlookeng-summary-ingress.yaml
- openlookeng-summary-service.yaml
- oauth-proxy.yaml
- namespace.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/oauth2-proxy
  newTag: a8f9261f77b224247863f12986a33b4959472309
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openlookeng/summary
  newTag: v1.0.20221230173957
