---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: openlookeng-search
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openlookeng/search:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: eshost
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: host
        - name: esusername
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: username
        - name: espassword
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: password
        - name: esport
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: port
        - name: depp
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: depp
        - name: teshost
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: teshost
        - name: tesport
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: tesport
        - name: tesusername
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: tesusername
        - name: tespassword
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: tespassword
        - name: X_ARMOR_BACKEND_BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: xarmor_backend_url 
        - name: X_ARMOR_BACKEND_APP_ID
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: xarmor_app_id 
        - name: X_ARMOR_BACKEND_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: xarmor_app_token
        - name: X_ARMOR_BACKEND_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: xarmor_tenant_id 
        - name: APPLICATION_PATH
          value: "/EaseSearch/target/classes/application.yml"
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /opengauss/application.yaml
          name: configmap-volume
          subPath: application.yaml
      volumes:
      - name: configmap-volume
        secret:
          secretName: search-secrets
