apiVersion: v1
imagePullSecrets:
- name: huawei-swr-image-pull-secret
kind: ServiceAccount
metadata:
  annotations:
    email: chenzeng765@163.com
    owner: chenzeng
  labels:
    app: openlookeng-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: openlookeng-jenkins
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.7.4
  name: jenkins
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    email: chenzeng765@163.com
    owner: chenzeng
  labels:
    app: openlookeng-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: openlookeng-jenkins
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.7.4
  name: jenkins-schedule-agents
  namespace: jenkins
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    email: chenzeng765@163.com
    owner: chenzeng
  labels:
    app: openlookeng-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: openlookeng-jenkins
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.7.4
  name: jenkins-schedule-agents
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-schedule-agents
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins