---
apiVersion: v1
kind: Service
metadata:
  annotations:
    email: chenzeng765@163.com
    owner: chenzeng
  labels:
    app: openlookeng-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: openlookeng-jenkins
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.7.4
  name: jenkins
  namespace: jenkins
spec:
  clusterIP: 10.247.191.168
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32717
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: jnlp
    nodePort: 32718
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: openlookeng-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
  sessionAffinity: None
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    email: chenzeng765@163.com
    owner: chenzeng
  labels:
    app: openlookeng-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: openlookeng-jenkins
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.7.4
  name: jenkins-agent
  namespace: jenkins
spec:
  clusterIP: 10.247.5.80
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: openlookeng-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
  sessionAffinity: None
  type: ClusterIP